### ISSUE TITLE
Simulation time step and max step are defined by maximum input signal time by default

### ISSUE THREAD

**Issue by dc14830** [TheSystemDevelopmentKit/spice#41]
Spice simulation parameters: stop, step and maxstep have a predefined ratio of 1, 1/1000 and 1/100.

Occasionally this will cause convergence issues in simulation.

**Comment by mkosunen** [comment]
@sporrasm can you check this with @dc14830 as you have more experience in editing spice. The usual branch-pullreguest procedure would do.

**Comment by sporrasm** [comment]
Closed by PR #42
