### ISSUE TITLE
Check array shape for sample type IO file

### ISSUE THREAD

**Issue by vlahtin** [TheSystemDevelopmentKit/spice#43]
The IO file fails generation if the input binary array does not have a shape, e.g. array.shape returns (4096,). In this case, array.reshape(-1,1) has to be run for it to return (4096,1), and after that the simulation works. 

Atleast a warning could be added pointing out that this may be the cause of it, or just trying to reshape the array in the case of the error.

**Comment by sporrasm** [comment]
+1 for forcing the reshape.

**Comment by sporrasm** [comment]
Fixed by commit d22ee60. Reshape is now forced on flat IO arrays of type 'sample'. Added warning print to indicate this.
