### ISSUE TITLE
Interactive waveform viewing for Spectre

### ISSUE THREAD

**Issue by sporrasm** [TheSystemDevelopmentKit/spice#5]
Let's implement interactive waveform viewing for Spectre also, as this makes it way easier to debug testbenches and circuits with SDK.

**Comment by sporrasm** [comment]
Plotting implement using Virtuoso Visualization and Analysis.

**Comment by sporrasm** [comment]
Launch Viva in parallel thread to have truly interactive plotting

**Comment by ojarvin** [comment]
This is closed by #28 where ezwave or viva is launched in a parallel thread.
