### ISSUE TITLE
Redundancy: Should use self.syntaxdict["simulatorcmd"]  in spicecmd, or remove that from dict.

### ISSUE THREAD

**Issue by mkosunen** [TheSystemDevelopmentKit/spice#7]

**Comment by ojarvin** [comment]
To me `self.syntaxdict["simulatorcmd"]` looks redundant, as the simulator is checked anyway and the needed flags depend on it (this dictionary value will be pretty much the same as `self.model`).

**Comment by mkosunen** [comment]
As per 47f1537dd4108 'simulatorcmd' is used as generic strng for calling the simulator, added with possible options, and it is not equivalent to self.model
