### ISSUE TITLE
Case conversion of instance name in subckt instantiation

### ISSUE THREAD

**Issue by mkosunen** [TheSystemDevelopmentKit/spice#9]
Ping @ojarvin, @sporrasm: Is there a particular reason, why the subcircuit name is converted to uppercase in module methods subckt and subinst? I think unnecessary conversions should be avoided.

**Comment by ojarvin** [comment]
No reason as far as I recall. I agree it doesn't need to be converted to uppercase.

**Comment by mkosunen** [comment]
Closed by 4bd50e1
